### ISSUE TITLE
error: unused function 'getTempFileProjDir' [-Werror,-Wunused-function]

### ISSUE THREAD

**Issue by yurivict** [schrodinger/coordgenlibs#100]
Build of coordgenlibs-2.0.3 fails:
```
/usr/ports/science/coordgenlibs/work/coordgenlibs-2.0.3/sketcherMinimizer.cpp:3520:15: error: unused function 'getTempFileProjDir' [-Werror,-Wunused-function]
static string getTempFileProjDir()
              ^
1 error generated.
```

clang-11
FreeBSD 13

**Comment by d-b-w** [comment]
This is an odd report, because that function is used 8 lines later. The function is defined (and used) conditionally on the `USE_MAEPARSER` macro.

Do you know if you have USE_MAEPARSER set in your cmake? Or, like, what it's set to?

**Comment by yurivict** [comment]
In the version 2.0.3 ```getTempFileProjDir()``` is only defined and not used.

```USE_MAEPARSER``` is defined.

**Comment by yurivict** [comment]
Sorry, port patch patched away the use of this function.

**Comment by d-b-w** [comment]
@yurivict  - if you _do_ have USE_MAEPARSER enabled, I'd recommend turning it off. The build should be tidier and more robust that way. It also sidesteps https://github.com/schrodinger/coordgenlibs/issues/64 completely.

**Comment by yurivict** [comment]
Ok, will do, thank you.
