### ISSUE TITLE
example target produce error under linux

### ISSUE THREAD

**Issue by ysagon** [schrodinger/coordgenlibs#14]
Hello, it seems there is an issue here

https://github.com/schrodinger/coordgenlibs/blob/f1c1100c8d555b53c9d4d7a83bfac90a36ffca17/CMakeLists.txt#L21

indeed, you are trying to build an executable named "example" (at least on Linux) and a directory with the same name already exist and thus produce an error.

Best

**Comment by lorton** [comment]
@ZontaNicola - do you want to address this?

**Comment by ZontaNicola** [comment]
Sure, opened a pull request
